# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "sum": "00_core.ipynb",
         "it_sum": "00_core.ipynb",
         "say_hi": "01_core.ipynb"}

modules = ["core.py",
           "core2.py"]

doc_url = "https://liucd.github.io/image_classification/"

git_url = "https://github.com/liucd/image_classification/tree/main/"

def custom_doc_links(name): return None
