# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'it_sum']

# Cell
def  say_hello ( to ):
    "向某人问好"
    return  f"Hello { to } !"

# Cell
import numpy as np
def it_sum(a, b):
    return a + b